
$script = <<'SCRIPT'
timedatectl set-timezone Europe/Amsterdam 
apt-get update
apt-get -y --autoremove upgrade
apt-get install -y make gcc g++ libssl-dev git libcurl4-gnutls-dev libusb-dev python3-dev zlib1g-dev libcereal-dev liblua5.3-dev uthash-dev libsqlite3-dev sqlite3 ntpdate python3-pytest python3-pytest-bdd

which cmake >/dev/null
if [ $? -eq 1 ]
then
	wget -nv https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2.tar.gz
	tar -xzvf cmake-3.19.2.tar.gz
	rm cmake-3.19.2.tar.gz
	cd cmake-3.19.2
	./bootstrap
	make -j5
	make install
	cd ..
	rm -Rf cmake-3.19.2
	cmake --version
else
	echo "=== Found CMake!"
	cmake --version
fi

if [ ! -d /usr/local/include/boost ]
then
	mkdir boost
	cd boost
	wget -nv https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.gz
	tar xfz boost_1_78_0.tar.gz
	cd boost_1_78_0/
	./bootstrap.sh
	./b2 stage threading=multi link=static --with-thread --with-system
	./b2 install threading=multi link=static --with-thread --with-system
	cd ../../
	sudo rm -Rf boost/
else
	echo "=== Found boost in /usr/local/include/boost !"
fi

if [ ! -d open-zwave-read-only ]
then
	git clone https://github.com/OpenZWave/open-zwave open-zwave-read-only
	cd open-zwave-read-only
	make -j5
	sudo make install
	cd ..
else
	echo "=== Local clone of OpenZWave GitHub repo found"
fi

echo "=== Cloning Domoticz from github"
git clone https://github.com/domoticz/domoticz
cd domoticz
echo "=== Switching to development branch"
git checkout development
echo "=== Building domoticz"
cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
make -j5
cd ..
chown -R vagrant:vagrant domoticz
echo "=== Configuring domoticz service"
sudo cp domoticz/domoticz.sh /etc/init.d
sudo chmod +x /etc/init.d/domoticz.sh
sudo sed -i 's/^USERNAME=.*/USERNAME=vagrant/'  /etc/init.d/domoticz.sh
sudo update-rc.d domoticz.sh defaults
sudo systemctl daemon-reload

echo "=== Downloading Volumio plugin to domoticz/plugins"
cd domoticz/plugins && git clone https://github.com/frepkovsky/Domoticz-Volumio-Plugin.git
chown -R vagrant:vagrant Domoticz-Volumio-Plugin

echo "=== Restarting domoticz service"
sudo systemctl restart domoticz

SCRIPT

# Create the VM with below settings
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.define "vgdomoticz"
  config.vm.hostname = "vmdomoticz"

  config.vm.network "forwarded_port", guest: 8080, host: 8080	# Domoticz
#  config.vm.network "forwarded_port", guest: 8443, host: 8443	# Domoticz SSL

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
    vb.name = "Domoticz-dev"
  end

  # And run the following 'script' (see above) to set things up
  config.vm.provision "shell", inline: $script
end
